print('Pick a number')
number1 = input()
print('Pick another number')
number2 = input()
print('Pick your last number')
number3 = input()
combine = (int(number1) + int(number2) + int(number3))
print(combine)

#print('Whats is your name?')
#name = input()
#print('Hello', name)
